services:
  foodplan-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./foodplan_service:/foodplan_service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASSWORD=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass